export const totalSteps = 6;

export const educationLevels = [
  { value: "10th", label: "10th Standard" },
  { value: "12th", label: "12th Standard" },
  { value: "diploma", label: "Diploma" },
  { value: "bachelor", label: "Bachelor's Degree" },
  { value: "masters", label: "Master's Degree" },
  { value: "phd", label: "PhD" },
];

export const interestAreas = {
  Engineering: [
    "Computer Science Engineering (CSE)",
    "Electrical & Electronics Engineering (EEE)",
    "Electronics & Communication Engineering (ECE)",
    "Mechanical Engineering",
    "Civil Engineering",
    "Chemical Engineering",
    "Aerospace Engineering",
    "Biomedical Engineering",
    "Information Technology (IT)",
    "Software Engineering",
    "Data Science & Engineering",
    "Artificial Intelligence & Machine Learning",
    "Cybersecurity Engineering",
  ],
  "Medicine & Healthcare": [
    "MBBS (Medicine)",
    "BDS (Dentistry)",
    "BAMS (Ayurveda)",
    "BHMS (Homeopathy)",
    "B.Pharm (Pharmacy)",
    "Nursing (B.Sc Nursing)",
    "Physiotherapy (BPT)",
    "Veterinary Science (B.V.Sc)",
    "Medical Laboratory Technology",
    "Radiology & Imaging Technology",
    "Optometry",
    "Psychology (Clinical)",
    "Public Health",
  ],
  "Business & Management": [
    "Business Administration (BBA)",
    "Commerce (B.Com)",
    "Chartered Accountancy (CA)",
    "Company Secretary (CS)",
    "Cost & Management Accountancy (CMA)",
    "Marketing & Sales",
    "Human Resources (HR)",
    "Finance & Banking",
    "International Business",
    "Entrepreneurship",
    "Digital Marketing",
    "Supply Chain Management",
    "Event Management",
  ],
  "Arts & Humanities": [
    "English Literature",
    "Journalism & Mass Communication",
    "Psychology",
    "Sociology",
    "Political Science",
    "History",
    "Philosophy",
    "Economics",
    "Fine Arts",
    "Performing Arts",
    "Creative Writing",
    "Film Studies",
    "Cultural Studies",
  ],
  "Science & Research": [
    "Physics",
    "Chemistry",
    "Mathematics",
    "Biology/Life Sciences",
    "Biotechnology",
    "Microbiology",
    "Environmental Science",
    "Forensic Science",
    "Marine Biology",
    "Astronomy & Astrophysics",
    "Geology",
    "Statistics",
    "Research & Development",
  ],
  "Design & Creative": [
    "Graphic Design",
    "UI/UX Design",
    "Fashion Design",
    "Interior Design",
    "Product Design",
    "Animation & VFX",
    "Game Design",
    "Photography",
    "Video Editing",
    "Architecture",
    "Textile Design",
    "Jewelry Design",
    "Industrial Design",
  ],
  "Law & Legal Studies": [
    "LLB (Bachelor of Laws)",
    "Corporate Law",
    "Criminal Law",
    "Constitutional Law",
    "International Law",
    "Cyber Law",
    "Intellectual Property Law",
    "Environmental Law",
    "Human Rights Law",
    "Legal Journalism",
    "Paralegal Studies",
  ],
  "Education & Teaching": [
    "B.Ed (Bachelor of Education)",
    "Elementary Education",
    "Special Education",
    "Educational Psychology",
    "Curriculum Development",
    "Educational Technology",
    "Adult Education",
    "Language Teaching",
    "Physical Education",
    "Early Childhood Education",
  ],
  "Agriculture & Food": [
    "Agriculture Engineering",
    "Horticulture",
    "Food Technology",
    "Agricultural Business",
    "Forestry",
    "Dairy Technology",
    "Fisheries Science",
    "Soil Science",
    "Plant Pathology",
    "Agricultural Economics",
    "Organic Farming",
    "Food Science & Nutrition",
  ],
  "Hospitality & Tourism": [
    "Hotel Management",
    "Tourism Management",
    "Culinary Arts",
    "Event Management",
    "Travel & Tourism",
    "Cruise Ship Management",
    "Resort Management",
    "Food & Beverage Management",
    "Aviation Hospitality",
    "Restaurant Management",
  ],
  "Sports & Fitness": [
    "Sports Management",
    "Physical Education",
    "Sports Medicine",
    "Fitness Training",
    "Sports Psychology",
    "Sports Journalism",
    "Yoga & Wellness",
    "Athletic Training",
    "Sports Nutrition",
    "Adventure Sports",
  ],
};

export const accommodationTypes = [
  { value: "hostel", label: "College Hostel" },
  { value: "pg", label: "Paying Guest" },
  { value: "home", label: "Stay at Home" },
  { value: "any", label: "Any Option" },
];
